### ISSUE TITLE
Async loaded modules support

### ISSUE THREAD

**Issue by sbekrin** [vitaliy-bobrov/angular-hot-loader#1]
Currently modules loaded with `requires.ensure(...)` are not working with hmr.

I can see that all directive / services / components / etc. are hooked by angular-hot-loader, but required module itslef is not executed (`.run` blocks are not firing).

Production build works fine. Any suggestions?

**Comment by sbekrin** [comment]
**Update:** I'm actually found the issue. It's not about async loading, but babel and how it's transforms the code. I've created #2 to fix that

**Comment by vitaliy-bobrov** [comment]
@sergeybekrin, I've tested it with some of my projects, looks and works fine for me. Thank you for PR :)
PR merged and included in 0.8.3 release.
