### ISSUE TITLE
Filter interceptor

### ISSUE THREAD

**Issue by zalishchuk** [vitaliy-bobrov/angular-hot-loader#15]
filter.js in interceptors folder just does nothing except retuning `this` instance and this one breaks my app, because angular can not find any registered filters.

Can you please add a simple interceptor for filter functions or stop modifying filters functions.

**Comment by vitaliy-bobrov** [comment]
@zalishchuk , I'll try to implement those method in the nearest future, but if you have ability you could create PR for that. Sorry, haven't enough time to work on this project as I'm focused on ng4 most of time

**Comment by vitaliy-bobrov** [comment]
@zalishchuk , I've added filter interception in v0.9.4 - please try it and let me know if everything ok. Thanks for helping improve project.

**Comment by zalishchuk** [comment]
@vitaliy-bobrov, application is now running, but I am also using [`babel-plugin-transform-runtime`](https://babeljs.io/docs/plugins/transform-runtime/), so I got another problem. Babel transformed classes are being detected by [`isClass`](https://github.com/vitaliy-bobrov/angular-hot-loader/blob/master/lib/angular-hot-loader.js#L45) function, but it doesn't provide a case when helpers are imported directly from `babel-runtime` package.

```
TypeError: Cannot call a class as a function
    at exports.default (eval at ../node_modules/babel-runtime/helpers/classCallCheck.js
    at def.controller.ModalController (eval at ./app/components/modal/modal.controller.js
```

**Comment by zalishchuk** [comment]
Pulled a fix for previous issue #19

**Comment by vitaliy-bobrov** [comment]
@zalishchuk, thanks for PR, I'll publish new version in the evening.

**Comment by vitaliy-bobrov** [comment]
Added to v0.9.6 release.
