### ISSUE TITLE
Directives interceptor breaks directives which expects injections

### ISSUE THREAD

**Issue by roypeled** [vitaliy-bobrov/angular-hot-loader#23]
```
ngModule.directive("test", function($filter) {
     let dateFilter = $filter("date");
     return {
            restrict: 'EA',
            scope: {
                test: "=",
            },
            template: "abc
        }
})
```

This will break angular-hot-loader because the interceptor runs the directive function upon registration without injections

**Comment by roypeled** [comment]
I understand that you run the directive function to get access to its template and controller definitions. Is there a way to wait for the angular module's run hook until this action is performed?

**Comment by vitaliy-bobrov** [comment]
Need some time to explore possible solutions. Feel free to create PR, if you have any ideas.

**Comment by miluoshi** [comment]
This commit in my fork fixes the problem with DI in a directive function: https://github.com/miluoshi/angular-hot-loader/commit/a7b7a158e28efaeda50c2cf994ee06a2831587d3

A directive function is wrapped in another function, which when called with proper injected dependencies will call original directive and send proper arguments (dependencies) into it.

**Comment by vitaliy-bobrov** [comment]
@miluoshi, thanks for fix, I'll apply it to the next release with few modifications.
