### ISSUE TITLE
loader does not work with strictDi = true

### ISSUE THREAD

**Issue by aserraric** [vitaliy-bobrov/angular-hot-loader#24]
I like to catch dependency issues early and thus run my angular app with strictDi : true
The injected hot loader code is not compatible with that approach (as it has no annotations) and apparently also resistant to automatic annotations (I use 'babel-loader' with the 'angularjs-annotate' plugin).

**Comment by vitaliy-bobrov** [comment]
@aserraric , currently I don't see possibility to implement strictDI support as hot module wraps hole app inside and dynamically invokes angular methods. But you can disable strict di for hmr builds using some environment variable, may it is not needed in development hmr mode.
