### ISSUE TITLE
Can't make the hot swapping work

### ISSUE THREAD

**Issue by NeverwinterMoon** [vitaliy-bobrov/angular-hot-loader#26]
I understand, this is more of a SO question, but I've seen other people being helped here, so I decided to give it a go.

`webpack.config.coffee`:
```
entry:
  booking: './src/app/index.js'
plugins: [
  new webpack.LoaderOptionsPlugin debug: true
  new HtmlWebpackPlugin
    filename: 'index.html'
    template: './src/index.jade'
    chunks: ['booking']
  new webpack.HotModuleReplacementPlugin()
  new webpack.NamedModulesPlugin()
]
resolve:
  extensions: ['.ts', '.js']
  modules: [
    'node_modules'
    path.resolve __dirname, 'src'
  ]
module:
  rules: [
      {
        test: /\.js$/
        exclude: /node_modules/
        use: [
          {
            loader: 'angular-hot-loader'
            options:
              rootElement: 'body'
              log: true
          }
          'babel-loader'
        ]
      }
      {
        test: /\.ts$/
        exclude: /node_modules/
        use: [
          {
            loader: 'angular-hot-loader'
            options:
              rootElement: 'body'
              log: true
            }
            {
            loader: 'awesome-typescript-loader'
            options:
              useBabel: true
            }
        ]
      }
  ]

devServer:
  hot: true
```

My babel is configured through `.babelrc`, so ng annotations are done there:
```
{
  "presets": [
    "es2015"
  ],
  "plugins": [
    "babel-plugin-transform-function-bind",
    "babel-plugin-transform-class-properties",
    "babel-plugin-angularjs-annotate"
  ]
}
```

The entry point looks like this:

```
'use strict'

import angular from 'angular'
import mobile from 'components/mobile/mobile'
import Util from './../util/util'
import 'app/index.scss'
import 'app/vendor.scss'

angular.module('miki', [
  mobile.name
])

angular.bootstrap(document.body, ['miki'], {
  strictDi: false
})
```

And this is a part `components/mobile/mobile.js`

```
'use strict'

import angular from 'angular'

import bookingPage from 'app/booking/booking'

export default angular.module('miki-main', [
  bookingPage.name
])
```

This is part of `app/booking/booking.js`:

```
'use strict'

import angular from 'angular'
import uiRouter from 'angular-ui-router'
import BookingController from './booking.controller'
import bookingTemplate from './booking.html'

export default angular.module('booking', [
  uiRouter
])
  .controller('BookingController', BookingController)
  .config(config)

function config($stateProvider) {
  'ngInject'


  $stateProvider
  .state('app.booking', {
      url: ''
      , views: {
        'content@': {
          template: bookingTemplate
          , controller: BookingController
        }
      }
  })
}
```

So, first of all, I had to change configuration of the project a bit to make AHL detect my ng modules - the following syntax was used everyhwere in the project before the change:

```
import { module } from 'angular'

export default module('booking', [])
```

But if `module` is used instead of `angular.module` I see that AHL fails to wrap the stuff around.

I've shown only a chunk of code, the rest of the code remained unchanged, so only the things I've shown are detected by AHL (mentioning this to make all the info available).

So, what I did after the configuration - I tried changing the `bookingTemplate` file (`'./booking.html'`). Hot reloader kicked in and didn't reload the whole app page like before. I saw that only the changed chunks were received and even saw that AHL did this bit:

```
this.logger('Reloading UI Router State', 'info');

var $state = elm.injector().get('$state');

$state.transitionTo...
```

But nothing was changed on screen.

**Comment by vitaliy-bobrov** [comment]
@NeverwinterMoon 

1. I've updated module RegExp in v0.9.10 - not it should work with `module('mod', [])` definitions.
2. Updated config block with state reload, it should update template after reload.

Please upgrade and give your feedback.

**Comment by NeverwinterMoon** [comment]
@vitaliy-bobrov Thanks! Will try it out today or tomorrow (depending on the work load) and let you know.

**Comment by NeverwinterMoon** [comment]
Just updating: haven't had a chance to try out yet because... struggling with a tight deadline at work. Hopefully, will be able to try in the next couple of days though.

**Comment by NeverwinterMoon** [comment]
@vitaliy-bobrov OK, finally I've tried it out. It seems the latest version (https://github.com/vitaliy-bobrov/angular-hot-loader/releases/tag/v0.9.10) breaks with TypeScript files.  As you can see in my original post, we have a mix of JS and TS files and the appropriate loaders - I've added `angular-hot-loader` to both of the pipelines. With 0.9.9 compilation passed, but with 0.9.10 compilation fails on TS files. This is what I get (example of one error only, it happens across multiple TS files):
```
ERROR in ./src/components/backToDesktop/backToDesktop.ts
Module parse failed: C:\DATA\Project\miki\node_modules\angular-hot-loader\lib\loader.js??ref--2-0!C:\DATA\Project\miki\node_modules\awesome-typescript-loader\dist\entry.js??ref--2-1!C:\DATA\Project\miki\src\components\backToDesktop\backToDesktop.ts Unexpected token (13:61)
You may need an appropriate loader to handle this file type.
| var backToDesktop_directive_1 = require("./backToDesktop.directive");
| var angular_1 = require("angular");
| exports.default = angular_1.hotAngular.test(module).module() {
|     return new backToDesktop_directive_1.default();
| }]);
 @ ./src/app/booking/booking.js 137:21-78
 @ ./src/components/mobile/mobile.js
 @ ./src/app/index.js
```

If I revert back to 0.9.9, it compiles, but hot reloading doesn't work.

Furthermore, if I try using AHL only for JS files, it compiles but I don't see the library outputing anything to console (as it was before). So, if I then try out the original syntax (import angular and then angular.module) with 0.9.10, then it doesn't compile too, now.

**Comment by vitaliy-bobrov** [comment]
@NeverwinterMoon, now I realised that I was wrong with RegExp changes, it matches webpack module as well, need to fix it. Other point is to investigate loader work from 2 pipelines.

**Comment by stevenmccord** [comment]
I get something like this when I try this:

```
  274 | 	}
  275 |
> 276 | 	hotAngular.test(module).module(angular.);
      | 	                                       ^
  277 |
  278 | }());
```

Looks like it might have something to do with the regex?

**Comment by feimosi** [comment]
I have the same issue, seems like a problem with the regex, see:
https://regex101.com/r/5s8kB4/1

I thought
 `(([_]?angular?[0-9]?[\\n]*[\s]*[\.\n\s]+(?:default[\.\n\s]+)?)?module\(([\'\"\w\.\/\\\(\)\n\-\,\[\] ]+)\))` 
would fix that, but then I get a whole bunch of new errors:
`Module build failed: error: couldn't process source due to parse error,Unexpected token (10:94)`
mostly for directive, filter, config and service files (not component).

**Comment by kkao88** [comment]
getting the same issue. lots of errors on es6 syntax with 0.9.10, no HMR with 0.9.9, though with logs on i can see it doing stuff, it just doesn't actually do the HMR

**Comment by Swiftwork** [comment]
Currently the RegExp has issues with the capture group. The change done in 0.9.10 added a second capture group which means it matches `angular.` instead of the expected module and dependencies. This can be fixed with prefixing the first capture group in the RegExp with `?:`, however there are still several multiline scenarios where the code still breaks or if the transpiles add additional syntaxing. I suggest documenting the process the loader.js file tries to accomplish so that this can be done manually instead.

**Comment by vitaliy-bobrov** [comment]
@feimosi, @kkao88, @stevenmccord, Could you give examples of angular module definitions that are passed to loader? I'll try to investigate where is the problem in RegExp.

**Comment by feimosi** [comment]
@vitaliy-bobrov check out the link I provided, the module is like this:
`angular.module('app.jhipster').factory('User', ["$resource", function (...){}]);`

**Comment by vitaliy-bobrov** [comment]
@feimosi , problem is in `factory` declaration with inline function, could be fixed easily replacing inline function with declaration like
```js
import 'UserService' from './user.service';

angular.module('app.jhipster')
  .factory('User', UserService);
```

I think better to mention this in README instead modifying RegExp.

**Comment by feimosi** [comment]
It's not possible, if you're using `ng-annotate` or even annotating manually - which is always the case if you want to minify your app.

**Comment by vitaliy-bobrov** [comment]
@feimosi , but ng-annotate adds `Service.$inject = [...]`

**Comment by feimosi** [comment]
@vitaliy-bobrov Hmm I need to check that and I'll get back to you.

**Comment by feimosi** [comment]
Sorry, I think that's not the case (inline functions). Even for non-inline declarations it breaks. I've tried to debug it further but I give up. In case someone wants to investigate it, I can recommend this tool:
https://regexly.chipto.io/

Here's output for the current regex:

![image](https://user-images.githubusercontent.com/5721520/32015254-cd0e51c4-b9c0-11e7-86ee-0e8718df2b90.png)

As you can see, in `regexp.exec(string)`  the index no. 1 is equal to `angular.`:

After trying to use the index `2`, I ended up with the following error
```
ERROR in ./src/app/components/index.js
Module build failed: TypeError: index.js: 
Cannot create property 'mappings' on string '{"version":3,"sources":["..."]}'
```

**Comment by kkao88** [comment]
@vitaliy-bobrov i'm using module definitions like 

```
export const SignInComponent = angular.module('echo.login.signIn', [
...
]).component('signIn', { ...
```

**Comment by midhunadarvin** [comment]
Is there a solution to this issue? I am using ng-annotate in my app configuration and i am getting this error.
```
Module build failed: SyntaxError: Unexpected token (45:54)

-> export default hotAngular.test(module).module(angular.)

```

**Comment by egucciar** [comment]
i removed ng-annotate and still getting issue with 0.9.11 any fix will be great!
