### ISSUE TITLE
When using angular-cookies - info is not a function angular 1.6.7

### ISSUE THREAD

**Issue by aiwha-dev** [vitaliy-bobrov/angular-hot-loader#27]
When using angular-cookies 1.6.7 with this plugin i'm recieving the following error

> angular-cookies.js?197f:20 Uncaught TypeError: hotAngular.module(...).info is not a function
>     at eval (angular-cookies.js?197f:20)
>     at eval (angular-cookies.js?197f:326)
>     at Object../node_modules/angular-cookies/angular-cookies.js (app.js?v=1516030363504:15704)
>     at __webpack_require__ (vendor.js?v=1516030363504:713)

please help

**Comment by vitaliy-bobrov** [comment]
@SamanthaAdrichem, `info` method interceptor was missed in hot loader. Implemented it in `v0.9.14`. Please check it and let me know if works fine for your project.

**Comment by aiwha-dev** [comment]
Yes that fixes that! Thnx
