### ISSUE TITLE
Webpack 2 support

### ISSUE THREAD

**Issue by jnatherley** [vitaliy-bobrov/angular-hot-loader#4]
Does this currently work for Webpack 2?

**Comment by vitaliy-bobrov** [comment]
Just tested it with one of my own projects that used Webpack 2 - and everything works fine for me. 
I'll update repo README with Webpack 2 instruction.
Feel free to open issue if something wrong for you.

**Comment by vitaliy-bobrov** [comment]
@jnatherley 
Just updated readme file.
