### ISSUE TITLE
Property 'hot' does not exist on type 'NodeModule'.

### ISSUE THREAD

**Issue by FDiskas** [vitaliy-bobrov/angular-hot-loader#5]
```
ERROR in [at-loader] src\app\Users\UsersModule.ts:1:26
    TS2339: Property 'hot' does not exist on type 'NodeModule'.
```
modules
```
angular-hot-loader@0.8.6
webpack@2.2.1
webpack-dev-server@2.4.1
```

**Comment by FDiskas** [comment]
p.s. using a typesript :x:

**Comment by FDiskas** [comment]
Probably missing type definition
```
@types/webpack-env
```

**Comment by vitaliy-bobrov** [comment]
@FDiskas, thanks.

**Comment by FDiskas** [comment]
But still could not get it work

**Comment by vitaliy-bobrov** [comment]
@FDiskas 
possible related issue solutions:
https://github.com/glenjamin/webpack-hot-middleware/issues/89
https://medium.com/@GiacomoRebonato/hot-module-reloading-with-typescript-and-react-9cc8768e8f24#.rtytl1hkc - article about react but issue related to code that added to app to enable HMR
```js
if (module.hot) {
      module.hot.accept();...
```

**Comment by xgz123** [comment]
a workaround is: 
`declare var module: any`
it's not perfect but it works😳

**Comment by ackvf** [comment]
Another workaround is
```
if ((module as any).hot) {
  (module as any).hot.accept('...
```

**Comment by jaysee260** [comment]
@ackvf this worked for me. thank you!

**Comment by nucab** [comment]
works fine :)

**Comment by chmelevskij** [comment]
While including `webpack-env` works, it causes a lot of clashing with other libraries. @ackvf solution works spot on.

**Comment by yyynnn** [comment]
Well, it could be dealt with like this:

```javascript
declare interface NodeModule {
  hot: {
    accept(path?: () => void, callback?: () => void): void
  }
}
```

**Comment by hcharley** [comment]
I had to make a slight modification to @yyynnn 's code to get it to work for me:

```ts
declare interface NodeModule {
  hot: {
    accept(path?: string, fn: () => void, callback?: () => void): void;
  };
}
```

I put this in my `globals.d.ts` file, just FYI.

**Comment by adameier** [comment]
adding `"webpack-env"` to the `types` array in my tsconfig.json got it working for me!

**Comment by aakilfernandes** [comment]
If you're running into this using react hot loader, might want to check this out:
https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#common-typescript-mistake

**Comment by tuzmusic** [comment]
Also you can save a bit of code by getting rid of `if (module.hot)` and just use
```typescript
if (process.env.NODE_ENV === 'development') {
  (module as any).hot?.accept('./App', render)
}
```
(I'm dealing with React, but same thing)

**Comment by tl-max** [comment]
Just add for this lines above 
`// @ts-ignore`

**Comment by MaximSemenov** [comment]
Just add for this lines above
```js
 @ts-ignore
 ```
